name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  API_KEY: ${{ secrets.config }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          npm run build  # Adjust this command based on your build setup
          echo "Your custom build command goes here"
        # Use the output files in the `./build` or `./dist` directory to deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Adjust this path based on your build output
